# Generated by Django 6.0.3 on 2026-04-06 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
    ]
